
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dabljar-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}

    restart: unless-stopped
    security_opt:
      - apparmor=unconfined