"""add user preferences and cascade delete

Revision ID: 7939187d2620
Revises: f1a2b3c4d5e6
Create Date: 2026-02-19 09:41:37.340745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7939187d2620'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_subscriptions_plan_id_fkey'), 'user_subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('user_subscriptions_user_id_fkey'), 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'user_subscriptions', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_subscriptions', 'subscription_plans', ['plan_id'], ['plan_id'], ondelete='CASCADE')
    # Add columns as nullable first
    op.add_column('users', sa.Column('default_domain', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('translation_style', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('default_voice', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('notif_completed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notif_credits', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notif_marketing', sa.Boolean(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE users SET default_domain = 'general' WHERE default_domain IS NULL")
    op.execute("UPDATE users SET translation_style = 'neutral' WHERE translation_style IS NULL")
    op.execute("UPDATE users SET default_voice = 'male1' WHERE default_voice IS NULL")
    op.execute("UPDATE users SET notif_completed = true WHERE notif_completed IS NULL")
    op.execute("UPDATE users SET notif_credits = true WHERE notif_credits IS NULL")
    op.execute("UPDATE users SET notif_marketing = false WHERE notif_marketing IS NULL")

    # Alter columns to be NOT NULL
    op.alter_column('users', 'default_domain', nullable=False)
    op.alter_column('users', 'translation_style', nullable=False)
    op.alter_column('users', 'default_voice', nullable=False)
    op.alter_column('users', 'notif_completed', nullable=False)
    op.alter_column('users', 'notif_credits', nullable=False)
    op.alter_column('users', 'notif_marketing', nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # Create the enum type if it doesn't exist
    op.execute("DO $$ BEGIN CREATE TYPE languages_enum AS ENUM ('ENGLISH', 'ARABIC'); EXCEPTION WHEN duplicate_object THEN null; END $$")
    
    # Drop default constraint first
    op.execute("ALTER TABLE users ALTER COLUMN preferred_language DROP DEFAULT")

    # Map existing string values to enum names
    op.execute("UPDATE users SET preferred_language = 'ENGLISH' WHERE preferred_language ILIKE 'en%'")
    op.execute("UPDATE users SET preferred_language = 'ARABIC' WHERE preferred_language ILIKE 'ar%'")
    # Set default for any remaining nulls or other values
    op.execute("UPDATE users SET preferred_language = 'ENGLISH' WHERE preferred_language NOT IN ('ENGLISH', 'ARABIC') OR preferred_language IS NULL")

    op.execute("ALTER TABLE users ALTER COLUMN preferred_language TYPE languages_enum USING preferred_language::languages_enum")
    op.alter_column('users', 'preferred_language',
               nullable=False,
               server_default='ENGLISH')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_users_facebook_id'), table_name='users', if_exists=True)
    op.drop_index(op.f('ix_users_google_id'), table_name='users', if_exists=True)
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS is_password_set")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS google_id")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS facebook_id")
    op.drop_constraint(op.f('videos_user_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_user_id_fkey'), 'videos', 'users', ['user_id'], ['user_id'])
    op.add_column('users', sa.Column('facebook_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_password_set', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_facebook_id'), 'users', ['facebook_id'], unique=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'preferred_language',
               existing_type=sa.Enum('ENGLISH', 'ARABIC', name='languages_enum'),
               type_=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'EN'::character varying"))
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'notif_marketing')
    op.drop_column('users', 'notif_credits')
    op.drop_column('users', 'notif_completed')
    op.drop_column('users', 'default_voice')
    op.drop_column('users', 'translation_style')
    op.drop_column('users', 'default_domain')
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('user_subscriptions_user_id_fkey'), 'user_subscriptions', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('user_subscriptions_plan_id_fkey'), 'user_subscriptions', 'subscription_plans', ['plan_id'], ['plan_id'])
    # ### end Alembic commands ###
