"""Add NMT translations

Revision ID: d4e6b1bc8db1
Revises: 7939187d2620
Create Date: 2026-02-22 23:43:56.387951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e6b1bc8db1'
down_revision: Union[str, Sequence[str], None] = '7939187d2620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('payments_subscription_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'user_subscriptions', ['subscription_id'], ['subscription_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_subscription_id_fkey'), 'payments', 'user_subscriptions', ['subscription_id'], ['subscription_id'])
    # ### end Alembic commands ###
